name: distractors
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - h5py==3.7.0
  - matplotlib==3.6.2
  - numpy==1.23.5
  - pandas==1.5.0
  - scipy==1.10.1
  - seaborn==0.11.2
  - statannot==0.2.3
  - statannotations==0.6.0
  - statsmodels==0.13.5
  - openpyxl
  - pytables==3.8.0
  - pip
  - pip:
    - scikit-learn==1.3.2
    - -e .